grab-your-java/coding-test-study

slowHuk9/stack_queue/src/stack_queue/backjoon_10828.java
slowHuk9/stack_queue/src/stack_queue/backjoon_9012.java
slowHuk9/stack_queue/src/stack_queue/backjoon_9012_count.java

[백준_10828] 스택 / Fail_ 시간초과 
[백준_9012] 스택 / 성공_ 스택 활용
[백준_9012_count] 스택 / 성공_ cnt 활용

백준 10828, 9012

---

newbieJanghan/day04/src/magnetic/Solution.java

첫 풀이에서는 각 테스트케이스 당 N 값 인풋을 읽지 않았지만
운 좋게 여러 테스트케이스를 통과했습니다.
오히려 테스트케이스 3개만 놓치니까, 첫 풀이에서의 실수를 발견하기가 어려웠습니다.
동료의 도움 덕분에 문제를 발견, 수정해서 풀 수 있었습니다

장한 / SWEA Magnetic

---

elsa-kim/sort/src/sort/bubble/BOJ_2750.java
elsa-kim/sort/src/sort/insert/BOJ_2750.java
elsa-kim/sort/src/sort/merge/BOJ_2751.java
elsa-kim/sort/src/sort/quick/BOJ_2750.java
elsa-kim/sort/src/sort/select/BOJ_2750.java
elsa-kim/stack_queue/src/stack_queue/구현/BOJ_10828.java
elsa-kim/stack_queue/src/stack_queue/구현/BOJ_18258.java
elsa-kim/stack_queue/src/stack_queue/활용/BOJ_2164.java
elsa-kim/stack_queue/src/stack_queue/활용/BOJ_9012.java

[#8 ] 문제
| 정렬| 메모리| 시간|
|--------|--------|--------|
| bubble | 22256kb | 356ms |
| Selection | 22368kb | 360ms |
| Insertion | 24248kb | 356ms |
| Quick | 메모리초과 | - | 
[#1]

소현 / 스택, 큐 & 정렬1 

---

newbieJanghan/day04/src/sort/BubbleSort.java
newbieJanghan/day04/src/sort/InsertionSort.java
newbieJanghan/day04/src/sort/QuickSort.java
newbieJanghan/day04/src/sort/SelectionSort.java

#8 문제
|정렬|메모리|시간
|--|--|--|
|Bubble Sort|22180kb|356ms|
|Selection Sort|22256kb|352ms|
|Insertion Sort|22396 kb|352ms|
|Quick Sort|22236kb|368ms|

장한 / 정렬을 직접 구현하자

---

newbieJanghan/day07/src/friends/Main.java

#41 
메모리 17732kb
시간 212ms
다른 분들의 풀이도 궁금합니다.

장한 / 1592. 영석이와 친구들

---

newbieJanghan/day07/src/honeycomb/Main.java

장한 / 2292. 벌집

---

newbieJanghan/day08/src/square/Main.java

#45
조건문 제어하는게 골치 아팠다.
일단 최대한 모든 경우를 다 커버할 수 있는 조건 제어문을 구성한 후
이후에 코드를 다듬어야겠다.

장한 / 2527_직사각형

---

SON1205/week3/.gitignore
SON1205/week3/src/BOJ10158.java
SON1205/week3/src/BOJ10163.java
SON1205/week3/src/BOJ11399.java
SON1205/week3/src/BOJ1158.java
SON1205/week3/src/BOJ13300.java
SON1205/week3/src/BOJ14696.java
SON1205/week3/src/BOJ17413.java
SON1205/week3/src/BOJ2839.java
SON1205/week3/src/BOJ2941.java
SON1205/week3/src/BOJ2999.java
SON1205/week3/src/BOJ3052.java
SON1205/week3/src/BOJ3985.java
SON1205/week3/src/BOJ8320.java
SON1205/week3/src/BOJ8958.java

#67 조건문이 많은데 코드 최적화를 어떻게 해야 할까
#68 .
#70 .
#69 .
#71 .
#72 .(메모리: 17744, 시간: 208)
#74 .(메모리: 19864, 시간: 832)
#75  제출 결과를 비교해보면 시간이 오래 걸린 편 (메모리: 22840, 시간: 592)
#76  Counting sort 사용 (메모리: 19864, 시간: 832)
#77 주석 방식대로 매번 나머지 연산을 실행하면 if문으로 처리한 것보다 약 3배 정도 차이 남 (메모리: 23584, 시간: 832)
#78 .(메모리: 183660, 시간: 1016)
#79 .(메모리: 21604, 시간: 288)
#80 '<'  이후 단어의 개수를 잘못 이해하고, swap 인덱스 조절 실패로 인한 시간 소요 (메모리: 38836, 시간: 1080)
#73 스스로 해결 못 함

진호 / WEEK03_A-지름길

---

slowHuk9/SWEA/src/BOJ_1244_3.java
slowHuk9/SWEA/src/SWEA_1220.java
slowHuk9/SWEA/src/SWEA_1954.java

#27 성공/ direction 진행방향에 따른 인덱스 증감값 설정 
x,y에 증감값을 적용한 nx ny 값(다음 이동 칸)이 배열 안에 있고 숫자가 없다면(초기값 0) 그대로 진행
nx, ny값이 배열을 벗어나거나 이미 숫자가 존재한다면 진행방향 수정 ( direction = (direction+1) % 4  )
진행방향 수정시키는 데에서 어려웠다..

혁규 / SWEA 1954 달팽이숫자

---

slowHuk9/BOJ/src/day0725/BOJ_1244.java

#37 pass : 대칭 스위치의 인덱스가 배열 범위를 벗어나는가 를 처음에 생각해낸게 다행인 것 같다

혁규 / 스위치 켜고 끄기

---

elsa-kim/BOJ/src/브론즈/BOJ_10163.java
elsa-kim/BOJ/src/브론즈/BOJ_13300.java
elsa-kim/BOJ/src/브론즈/BOJ_14696.java
elsa-kim/BOJ/src/브론즈/BOJ_1592.java
elsa-kim/BOJ/src/브론즈/BOJ_2292.java
elsa-kim/BOJ/src/브론즈/BOJ_2309.java
elsa-kim/BOJ/src/브론즈/BOJ_2798.java
elsa-kim/BOJ/src/브론즈/BOJ_2810.java
elsa-kim/BOJ/src/브론즈/BOJ_2851.java
elsa-kim/BOJ/src/브론즈/BOJ_2999.java
elsa-kim/BOJ/src/브론즈/BOJ_3052.java
elsa-kim/BOJ/src/브론즈/BOJ_3985.java
elsa-kim/BOJ/src/브론즈/BOJ_8320.java
elsa-kim/BOJ/src/브론즈/BOJ_8958.java
elsa-kim/BOJ/src/실버/BOJ_10158.java
elsa-kim/BOJ/src/실버/BOJ_11399.java
elsa-kim/BOJ/src/실버/BOJ_1158.java
elsa-kim/BOJ/src/실버/BOJ_1244.java
elsa-kim/BOJ/src/실버/BOJ_17413.java
elsa-kim/BOJ/src/실버/BOJ_2477.java
elsa-kim/BOJ/src/실버/BOJ_2527.java
elsa-kim/BOJ/src/실버/BOJ_2563.java
elsa-kim/BOJ/src/실버/BOJ_2567.java
elsa-kim/BOJ/src/실버/BOJ_2839.java
elsa-kim/BOJ/src/실버/BOJ_2941.java

#41 #37 #42 #43 #44 #45 #46 #47 #48 #49 #66 #67 #68 #69 #70 #71 #72 #74 #75 #76 #77 #78 #79 #80 #73

소현 / 첫째주 BOJ

---

slowHuk9/BOJ/src/day0725/BOJ_1592.java

#41  pass : 배열 인덱스 계산 식 떠올리는 데에서 시간이 좀 걸렸다

혁규 / 영식이와 칭구들

---

slowHuk9/BOJ/src/day0726/BOJ_2309.java

#43 pass : 처음에 가짜 난쟁이 구분하는 방법을 떠올린 게 큰 것 같다. 브루트 포스인가 참고해서 풀긴 했는데 
해쉬맵 쓰는게 시간복잡도가 좋다고 해서 나중에 다시 해쉬맵으로 ..

혁규 / 일곱난장이

---

slowHuk9/BOJ/src/BOJ_10163.java
slowHuk9/BOJ/src/BOJ_11399.java
slowHuk9/BOJ/src/BOJ_13300.java
slowHuk9/BOJ/src/BOJ_14696.java
slowHuk9/BOJ/src/BOJ_2839.java
slowHuk9/BOJ/src/BOJ_8958.java

설탕배달 BOJ_2839 / #74 pass : 생각 속에서는 분명 되는데 구현 하려고 보면 아닌 것 같고.. 무한뺑뺑이에 시간이 좀 걸렸다.
색종이 BOJ_10163 / #75 pass : width, height 거꾸로 더해놓고 왜 안되지 했다. 에효..
ATM퀴즈 BOJ_11399 / #76 pass : 무난
방배정 BOJ_13300 / #78 pass : 소현누님이 종종 2차원 배열로 한꺼번에 관리하길래 따라해봤다. 되게 편한듯?!? 
딱지놀이 BOJ_14696 / #79 pass : 무승부 D를 판단할때, 배열 간 요소들이 서로 같은지 비교해주는 메서드가 있는지 검색했다가 진짜 있길래 써봤다. 
```Arrays.equals(Acount, Bcount)```

혁규 / Week03 BOJ

---

newbieJanghan/day08/src/snow_white/Main.java

장한 / 2309, 일곱난쟁이

---

newbieJanghan/day05/src/switch_1244/Main.java

#37 
실패했던 풀이에서 뭐가 문제였는지 잘 모르겠다.

장한 / 1244. 스위치 켜고 끄기

---

newbieJanghan/day10/src/croatian_alphabet/Main.java
newbieJanghan/day10/src/cup_holder/Main.java
newbieJanghan/day10/src/super_mario/Main.java
newbieJanghan/day11/src/secret_email/Main.java
newbieJanghan/day12/src/how_to_make_square/Main.java
newbieJanghan/day12/src/modular/Main.java
newbieJanghan/day12/src/ox_quiz/Main.java
newbieJanghan/day12/src/roll_cake/Main.java
newbieJanghan/day13/src/ant/Main.java
newbieJanghan/day13/src/ant/Main2.java

#73 
다른 분 컴퓨터에서는 시간 초과 안 되고 통과하는데
왜 내 꺼에서는 시간초과되는지 참 ㅋㅋㅋ

장한 / 개미 [#73]

---

slowHuk9/BOJ/src/Week2/BOJ_2941.java

#67  pass: 이렇게 푸는 거 말고.. 있나,,
마지막 s , z 의 if else에서 else에 cnt++을 빼먹어서  확인잘하기

혁규 / 크로아티아 

---

newbieJanghan/day10/src/croatian_alphabet/Main.java
newbieJanghan/day10/src/cup_holder/Main.java
newbieJanghan/day10/src/super_mario/Main.java
newbieJanghan/day11/src/secret_email/Main.java
newbieJanghan/day12/src/how_to_make_square/Main.java
newbieJanghan/day12/src/modular/Main.java
newbieJanghan/day12/src/ox_quiz/Main.java
newbieJanghan/day12/src/roll_cake/Main.java
newbieJanghan/day16/src/ATM/Main.java
newbieJanghan/day16/src/Sugar/Main.java
newbieJanghan/day16/src/josephus/Main.java
newbieJanghan/day16/src/paper3/Main.java
newbieJanghan/day16/src/room/Main.java
newbieJanghan/day17/src/ddakjji/Main.java
newbieJanghan/day17/src/word_flip/Main.java

#49 
#66 
#67 
#68 
#69 
#70 
#71 
#72 
#74 
#75
#76 
#77 
#78
#79 
#80

장한 / milestone - BOJ for A

---

slowHuk9/BOJ/src/Week2/BOJ_2851.java

#66 pass :  for문을 돌다가 특정 조건에 달했을 때는 break 꼭 써주기

혁규 / 슈퍼마리오

---

SON1205/swea/src/swea/SWEA11315.java
SON1205/swea/src/swea/SWEA1204.java
SON1205/swea/src/swea/SWEA1215.java
SON1205/swea/src/swea/SWEA1218.java
SON1205/swea/src/swea/SWEA1220.java
SON1205/swea/src/swea/SWEA1289.java
SON1205/swea/src/swea/SWEA1493.java
SON1205/swea/src/swea/SWEA1859.java
SON1205/swea/src/swea/SWEA1860.java
SON1205/swea/src/swea/SWEA1940.java
SON1205/swea/src/swea/SWEA1954.java
SON1205/swea/src/swea/SWEA1961.java
SON1205/swea/src/swea/SWEA1974.java
SON1205/swea/src/swea/SWEA1979.java
SON1205/swea/src/swea/SWEA1984.java
SON1205/swea/src/swea/SWEA2001.java
SON1205/swea/src/swea/SWEA2005.java
SON1205/swea/src/swea/SWEA2007.java
SON1205/swea/src/swea/SWEA2805.java
SON1205/swea/src/swea/SWEA3499.java
SON1205/swea/src/swea/SWEA4047.java
SON1205/swea/src/swea/SWEA4698.java
SON1205/swea/src/swea/SWEA4789.java
SON1205/swea/src/swea/SWEA5356.java
SON1205/swea/src/swea/SWEA5432.java
SON1205/swea/src/swea/SWEA6485.java
SON1205/swea/src/swea/SWEA7087.java
SON1205/swea/src/swea/SWEA7236.java
SON1205/swea/src/swea/SWEA7272.java
SON1205/swea/src/swea/SWEA7964.java

#9 .
#21 .
#24 배열을 만들고 탐색하려고 하였으나 시간이 너무 오래 걸렸던 시도가 있었음
#25 .
#26 더욱 간결하게 작성하고 싶은 생각이 들었음
#27 배열을 자유롭게 다룬다는 느낌이 들진 않았음
#29 .
#30 혼자만의 무한 루프에 빠져 허우적거리다 나옴
#31 간결한 코드는 아닌 느낌
#33 .
#34 2차원 배열 누적합으로 풀어봄
#35 .
#55 .
#56 입력을 int로 받아서 나눗셈, 나머지 연산을 사용하려 했음
#57 .
#81 코드가 너무 김
#82 .
#96 .
#98 스택이라는 힌트를 몰랐다면 고민을 많이 했을 듯
#99 .
#100 map 사용해서 풀어 봄
#102 .
#103 조건문이 복잡함

진호 / SWEA 선정 문제 풀이

---

slowHuk9/SWEA/src/SWEA_11315_오목판정/Solution.java
slowHuk9/SWEA/src/SWEA_11315_오목판정/test.java
slowHuk9/SWEA/src/SWEA_1204/Solution.java
slowHuk9/SWEA/src/SWEA_1215/Solution.java
slowHuk9/SWEA/src/SWEA_1218/Solution.java
slowHuk9/SWEA/src/SWEA_12712.java
slowHuk9/SWEA/src/SWEA_1859/Solution.java
slowHuk9/SWEA/src/SWEA_1860/Solution.java
slowHuk9/SWEA/src/SWEA_1940.java
slowHuk9/SWEA/src/SWEA_1974/Solution.java
slowHuk9/SWEA/src/SWEA_1979.java
slowHuk9/SWEA/src/SWEA_1984.java
slowHuk9/SWEA/src/SWEA_2001/Solution.java
slowHuk9/SWEA/src/SWEA_2805/Solution.java
slowHuk9/SWEA/src/SWEA_4047/Solution.java
slowHuk9/SWEA/src/SWEA_5356/Solution.java
slowHuk9/SWEA/src/SWEA_6485.java
slowHuk9/SWEA/src/SWEA_7087/Solution.java

[#26] 가랏RC카 pass / 19,984 kb 127 ms

혁규 / SWEA 문제풀이
